import {
  Crown,
  Gavel,
  UserCog,
  Scale,
  Wallet,
  ScrollText,
  MessageSquare,
  Users,
  Calendar,
  CheckSquare,
  Calculator,
  Trophy,
  ClipboardCheck,
} from "lucide-react";

 

const executives = [
  {
    name: "H.E. Judah Larbi Sarpong",
    role: "President",
    image: "/images/executives/Larbi.jpg?height=400&width=400",
    icon: Crown,
    description: "Leading the association's mission.",
  },
  {
    name: "H.E. Johosaphat Lucky Owusu Ansah",
    role: "Vice President",
    image: "/images/executives/Lucky.jpg?height=400&width=400",
    icon: UserCog,
    description: "Supporting innovative initiatives",
  },
  {
    name: "Nsiah Emmanuel",
    role: "Special Advisor",
    image: "/images/executives/Nsiah.jpg?height=400&width=400",
    icon: Calendar,
    description: "Planning and executing events",
  },
  {
    name: "Faruzatu Tahiru",
    role: "Women’s Commissioner",
    image: "/images/executives/Faruzatu.jpg?height=400&width=400",
    icon: Calendar,
    description: "Planning and executing events",
  },
  {
    name: "Hon. Aidoo Kwabena Eyiah",
    role: "Organizer",
    image: "/images/executives/Aidoo.jpg?height=400&width=400",
    icon: Calendar,
    description: "Planning and executing events",
  },
  {
    name: "Hon. Amoah Boadi Mensah",
    role: "Deputy Organizer",
    image: "/images/executives/vardy.jpg?height=400&width=400",
    icon: Calendar,
    description: "Planning and executing events",
  },
  {
    name: "Hon. Yeboah Emmanuel Osei",
    role: "Sports Chairman",
    image: "/images/executives/Yeboah.jpg?height=400&width=400",
    icon: Trophy,
    description:
      "Coordinating sports activities and promoting physical wellness",
  },
  {
    name: "Hon. Bright Nyaaba Akanzebe",
    role: "Project Manager",
    image: "/images/executives/Bright.jpg?height=400&width=400",
    icon: ClipboardCheck,
    description: "Overseeing technical projects and student innovations",
  },
  {
    name: "Hon. Harris Abdallah Musah",
    role: "Deputy Project Manager",
    image: "/images/executives/Harris.jpg?height=400&width=400",
    icon: ClipboardCheck,
    description: "Overseeing technical projects and student innovations",
  },
  {
    name: "Hon. Emmanuella Ewura Abena Filson",
    role: "General Secretary",
    image: "/images/executives/Tracy.jpg?height=400&width=400",
    icon: ScrollText,
    description: "Assisting in administrative tasks and record-keeping",
  },
  {
    name: "Hon. Tracy Edem Amevor",
    role: "Deputy General Secretary",
    image: "/images/executives/Tracy.jpg?height=400&width=400",
    icon: ScrollText,
    description: "Assisting in administrative tasks and record-keeping",
  },
  {
    name: "Otubah Richmond",
    role: "Treasurer",
    image: "/images/executives/Otubah.jpg?height=400&width=400",
    icon: ScrollText,
    description: "Assisting in administrative tasks and record-keeping",
  },
  {
    name: "Hon. Owusu Francis",
    role:"Deputy Treasurer",
    image:"/images/executives/francis.jpg?width=400&height=400",
    icon: Wallet,
    description: " Managing association's financially resources",
  },
  {
    name: "Hon. Owusu Dennis Asare",
    role: "Senate Chairman",
    image: "/images/executives/dennis.jpg?height=400&width=400",
    icon: Gavel,
    description: "Overseeing legislative matters within the association",
  },
  {
    name: "Hon. Raphael Otsiwah-Arhin",
    role: "Judicial Chairman",
    image: "/images/executives/Raphael.jpg?height=400&width=400",
    icon: Scale,
    description: "Ensuring fairness and justice in the association",
  },
  {
    name: "Hon. Nusetor Mawuwornu Daniel",
    role: "Electoral Chairman",
    image: "/images/executives/Nusetor.jpg?height=400&width=400",
    icon: CheckSquare,
    description: "Managing and overseeing electoral processes",
  },
  {
    name: "Hon. Godwin Nvidah",
    role: "Audit Chairman",
    image: "/images/executives/Godwin.jpg?height=400&width=400",
    icon: Calculator,
    description: "Ensuring financial transparency and accountability",
  },
  {
    name: "Hon. Gad Odoi Alert",
    role: "Communications Officer",
    image: "/images/executives/Gad.jpg?height=400&width=400",
    icon: Calculator,
    description: "Ensuring financial transparency and accountability",
  },
];

export default executives;

