import {
  Crown,
  Gavel,
  UserCog,
  Scale,
  Wallet,
  ScrollText,
  MessageSquare,
  Users,
  Calendar,
  CheckSquare,
  Calculator,
  Trophy,
  ClipboardCheck,
} from "lucide-react";

const executives = [
  {
    name: "HE.John Doe",
    role: "President",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Crown,
    description: "Leading ACSES towards technological excellence",
  },
  {
    name: "HE. Jane Smith",
    role: "Vice President",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: UserCog,
    description: "Supporting innovative initiatives",
  },
  {
    name: "Mike Johnson",
    role: "Financial Secretary",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Wallet,
    description: "Managing association resources",
  },
  {
    name: "Sarah Williams",
    role: "General Secretary",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: ScrollText,
    description: "Coordinating administrative affairs",
  },
  {
    name: "David Brown",
    role: "Communications Officer",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: MessageSquare,
    description: "Handling internal and external communications",
  },
  {
    name: "Emily Davis",
    role: "Women's Commissioner",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Users,
    description: "Promoting women in technology",
  },
  {
    name: "Alex Wilson",
    role: "Organizer",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Calendar,
    description: "Planning and executing events",
  },
  {
    name: "Chris Thompson",
    role: "Sports Chairman",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Trophy,
    description:
      "Coordinating sports activities and promoting physical wellness",
  },
  {
    name: "Rachel Chen",
    role: "Project Manager",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: ClipboardCheck,
    description: "Overseeing technical projects and student innovations",
  },
  {
    name: "Linda Harper",
    role: "Assistant General Secretary",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: ScrollText,
    description: "Assisting in administrative tasks and record-keeping",
  },
  {
    name: "Daniel Lee",
    role: "Senate Chairman",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Gavel,
    description: "Overseeing legislative matters within the association",
  },
  {
    name: "Grace Taylor",
    role: "Judicial Chairman",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Scale,
    description: "Ensuring fairness and justice in the association",
  },
  {
    name: "Oliver Harris",
    role: "Electoral Chairman",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: CheckSquare,
    description: "Managing and overseeing electoral processes",
  },
  {
    name: "Sophia Carter",
    role: "Audit Chairman",
    image: "/images/placeholder.svg?height=400&width=400",
    icon: Calculator,
    description: "Ensuring financial transparency and accountability",
  },
];

export default executives;
