const galleryItems = [
  {
    id: 1,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(87).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 2,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-79.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 3,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-81.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 4,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-76.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 5,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-77.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 6,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-46.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 7,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-45.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 8,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-43.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 9,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-33.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 10,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-35.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 11,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-42.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 12,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-22.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 13,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-12.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 14,
    src: "https://acses-cdn.onrender.com/gallery/acses24/ACSES24-2.JPG",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 15,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(92).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 16,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(28).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 17,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(93).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 18,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(7).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 19,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(3).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 20,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(24).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 21,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(22).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 22,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(20).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 23,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(90).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 24,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(75).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 25,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(85).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 26,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(71).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 27,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(83).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 28,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(67).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 29,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(77).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 30,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(84).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 31,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(79).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 32,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(59).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 33,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(62).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 34,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(70).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 35,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(56).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 36,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(55).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 37,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(45).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 38,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(49).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 39,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(41).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 40,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(42).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 41,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(66).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 42,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(65).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 43,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(40).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 44,
    src: "https://acses-cdn.onrender.com/gallery/bits2bytes/Bits2Bytes_BraoseiStudios%20(33).jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  }
];

export default galleryItems;
