const galleryItems = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736214005/photo_2025-01-07_01-38-55_queko3.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213938/ACSES24-79_afirvy.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213937/ACSES24-81_nbuwcp.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 4,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213936/ACSES24-76_bb2lvi.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 5,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213936/ACSES24-77_wf6lxm.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 6,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213931/ACSES24-46_tklrtm.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 7,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213911/ACSES24-45_jpvg2m.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 8,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213904/ACSES24-43_ohbpox.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 9,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213903/ACSES24-33_wjhslr.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 10,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213903/ACSES24-35_oop3bc.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 11,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213902/ACSES24-42_pwdqxq.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 12,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213901/ACSES24-22_mde4er.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 13,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213900/ACSES24-12_xnv0o3.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 14,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736213900/ACSES24-2_h9zamk.jpg",
    alt: "ACSES WEEK 24",
    description: "Our annual week celebration",
    category: "Events",
  },
  {
    id: 15,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204102/Bits2Bytes_BraoseiStudios_92_oldgtq.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 16,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204100/Bits2Bytes_BraoseiStudios_28_lw7xzi.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 17,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204099/Bits2Bytes_BraoseiStudios_93_pkm6hf.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 18,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204098/Bits2Bytes_BraoseiStudios_7_kpl0xi.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 19,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204082/Bits2Bytes_BraoseiStudios_3_crgf1o.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 20,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204074/Bits2Bytes_BraoseiStudios_24_ujzne1.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 21,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204061/Bits2Bytes_BraoseiStudios_22_b6nvej.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 22,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204045/Bits2Bytes_BraoseiStudios_20_qsf9oa.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 23,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204030/Bits2Bytes_BraoseiStudios_90_ownmrl.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 24,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204017/Bits2Bytes_BraoseiStudios_75_mreror.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 25,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204006/Bits2Bytes_BraoseiStudios_85_wf7oig.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 26,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204010/Bits2Bytes_BraoseiStudios_71_o26oxq.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 27,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736204003/Bits2Bytes_BraoseiStudios_83_nlqczd.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 28,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203998/Bits2Bytes_BraoseiStudios_67_rrzofj.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 29,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203982/Bits2Bytes_BraoseiStudios_77_fniyu6.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 30,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203982/Bits2Bytes_BraoseiStudios_84_r4ea6z.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 31,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203967/Bits2Bytes_BraoseiStudios_79_kllfo3.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 32,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203961/Bits2Bytes_BraoseiStudios_59_qxbllo.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 33,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203959/Bits2Bytes_BraoseiStudios_62_em7nfp.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 34,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203959/Bits2Bytes_BraoseiStudios_70_sldrlw.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 35,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203946/Bits2Bytes_BraoseiStudios_56_miizyt.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 36,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203941/Bits2Bytes_BraoseiStudios_55_egov7g.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 37,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203929/Bits2Bytes_BraoseiStudios_45_qjzdjs.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 38,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203926/Bits2Bytes_BraoseiStudios_49_mzelpy.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 39,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203907/Bits2Bytes_BraoseiStudios_41_pnqzgm.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 40,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203900/Bits2Bytes_BraoseiStudios_42_jybkpj.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 41,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203897/Bits2Bytes_BraoseiStudios_66_jbzmeu.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 42,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203896/Bits2Bytes_BraoseiStudios_65_cimzk2.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 43,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203885/Bits2Bytes_BraoseiStudios_40_mdiinz.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  },
  {
    id: 44,
    src: "https://res.cloudinary.com/dwcoos4ry/image/upload/q_auto/v1736203873/Bits2Bytes_BraoseiStudios_33_oqkuno.jpg",
    alt: "Bits to Bytes",
    description: "A seminar for capacity building in tech",
    category: "Seminar",
  }
];

export default galleryItems;
