const galleryItems = [
  {
    id: 1,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Tech Workshop 2024",
    description: "Students participating in our annual coding workshop",
    category: "Events",
  },
  {
    id: 2,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Hackathon Winners",
    description: "Winners of ACSES Hackathon 2024",
    category: "Competitions",
  },
  {
    id: 3,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Guest Lecture",
    description: "Industry expert sharing insights on AI",
    category: "Lectures",
  },
  {
    id: 4,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Team Building",
    description: "ACSES members during team building activity",
    category: "Social",
  },
  {
    id: 5,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Project Showcase",
    description: "Students presenting their final year projects",
    category: "Events",
  },
  {
    id: 6,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Industry Visit",
    description: "Visit to leading tech company",
    category: "Field Trips",
  },
  {
    id: 7,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Award Ceremony",
    description: "Annual ACSES awards night",
    category: "Events",
  },
  {
    id: 8,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Programming Contest",
    description: "Students during the coding competition",
    category: "Competitions",
  },
  {
    id: 9,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Community Service",
    description: "ACSES members teaching coding to school students",
    category: "Outreach",
  },
  {
    id: 10,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Tech Quiz",
    description: "Students participating in tech quiz competition",
    category: "Competitions",
  },
  {
    id: 11,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Guest Lecture",
    description: "Industry expert sharing insights on AI",
    category: "Lectures",
  },
  {
    id: 12,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Team Building",
    description: "ACSES members during team building activity",
    category: "Social",
  },
  {
    id: 13,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Project Showcase",
    description: "Students presenting their final year projects",
    category: "Events",
  },
  {
    id: 14,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Industry Visit",
    description: "Visit to leading tech company",
    category: "Field Trips",
  },
  {
    id: 15,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Award Ceremony",
    description: "Annual ACSES awards night",
    category: "Events",
  },
  {
    id: 16,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Programming Contest",
    description: "Students during the coding competition",
    category: "Competitions",
  },
  {
    id: 17,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Community Service",
    description: "ACSES members teaching coding to school students",
    category: "Outreach",
  },
  {
    id: 18,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Tech Quiz",
    description: "Students participating in tech quiz competition",
    category: "Competitions",
  },
  {
    id: 19,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Guest Lecture",
    description: "Industry expert sharing insights on AI",
    category: "Lectures",
  },
  {
    id: 20,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Team Building",
    description: "ACSES members during team building activity",
    category: "Social",
  },
  {
    id: 21,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Project Showcase",
    description: "Students presenting their final year projects",
    category: "Events",
  },
  {
    id: 22,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Industry Visit",
    description: "Visit to leading tech company",
    category: "Field Trips",
  },
  {
    id: 23,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Award Ceremony",
    description: "Annual ACSES awards night",
    category: "Events",
  },
  {
    id: 24,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Programming Contest",
    description: "Students during the coding competition",
    category: "Competitions",
  },
  {
    id: 25,
    src: "/images/placeholder.svg?height=400&width=600",
    alt: "Community Service",
    description: "ACSES members teaching coding to school students",
    category: "Outreach",
  },
];

export default galleryItems;
